# Hints:
#  Can you ping/SSH to the new instance?
#  Does our OpenStack host VM have property connectivity? 
#  Where can we configure network access to/from instances?
#  What security group does this VM belong to? 
#  What rules are present for this security group?
# 
#
#
#
#
# (the first 10 lines are the hint, so pad with empty lines)

- hosts: all
  become: true
  tasks: 
  - name: exercise setup step 1
    yum: name=python-pip state=present

  - name: exercise setup step 2
    pip: name=shade  

  - name: exercise setup step 3
    shell: "openstack --os-auth-url=$(grep OS_AUTH_URL /root/keystonerc_admin | awk -F'=' '{print $2}') --os-username=$(grep OS_USERNAME /root/keystonerc_admin | awk -F'=' '{print $2}') --os-password=$(grep OS_PASSWORD /root/keystonerc_admin | awk -F'=' '{print $2}') --os-project-name=admin  user set --password rackspace admin"
    ignore_errors: yes

  - name: exercise setup step 4
    lineinfile: dest=/root/keystonerc_admin regexp='^export OS_PASSWORD=.*' line='export OS_PASSWORD=rackspace'

  - name: exercise setup step 5
    os_server: 
      state: present
      auth:
        auth_url: http://10.0.2.15:5000/v2.0/
        username: admin
        password: rackspace
        project_name: admin
      name: vm1 
      image: cirros
      flavor: 1
      network: private
      auto_ip: yes
 

  - name: Description
    debug: 
      msg: >
        A user has spun up a new VM (vm1) and is unable to ping
        or connect to it. Troubleshoot to ensure that we can ping
        and SSH to the instance. 

#
# !!!!!!!!!!!!!!!!!!!!!
# !!! SPOILER ALERT !!!
# !!!!!!!!!!!!!!!!!!!!!
#  
# Solution: 
# The default security group rules haven't been created. Fix like so: 
# nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0
# nova secgroup-add-rule default tcp 22 22 0.0.0.0/0
# 
#
