# Hints:
#  Are the neutron components running?
#  Try to restart the services and notice
#  if there's some permission that's missing.
#  Could it be a security feature?
# 
#
#
#
#
# (the first 10 lines are the hint, so pad with empty lines)

- hosts: all
  become: true
  tasks:
  
  - name: setting up exercise
    selinux: policy=targeted state=enforcing

  - name: setting up the exercise (step 1 of 2)
    file: path=/usr/bin/neutron-{{ item }}-agent setype=gnome_home_t
    with_items:
      - dhcp 
      - l3
      - metadata
      - metering
      - openvswitch
    
  - name: setting up the exercise (step 2 of 2)
    file: path=/etc/neutron setype=lvm_metadata_t recurse=yes

  - name: add task file to /root/breakfix.txt
    blockinfile: 
      dest: /root/breakfix.txt
      create: yes
      insertbefore: BOF
      block: | 
        We cannot access the OpenStack host, log in via remote console and troubleshoot. 
        Hints can be found in the /root/hint{1,2} files
        The solution can be found in /root/solution.txt

  - name: add hints file to /root/hint1.txt 
    blockinfile: 
      dest: /root/hint1.txt
      create: yes
      insertbefore: BOF
      block: |
        What happens when we try to SSH to the host? 
        When you log in via console, do networking services (including neutron) look healthy?

  - name: add hints file to /root/hint2.txt
    blockinfile: 
      dest: /root/hint2.txt
      create: yes
      insertbefore: BOF
      block: |
        What happens when you try to restart Neutron services?
        Could there be any security features getting in our way?

  - name: add answer file to /root/solution.txt
    blockinfile: 
      dest: /root/solution.txt
      create: yes
      insertbefore: BOF
      block: | 
        The SELinux types for some Neutron files have been messed with! Fix using 'restorecon': 
          # restorecon -Rv /etc/neutron/
          # restorecon -v /usr/bin/neutron-*


  - name: Description
    debug:
      msg: >
        Breakfix operation complete! To access the BF1 VM: 'ssh -p 2222 root@127.0.0.1' (password: rpcr). Task file is in /root/breakfix.txt, hint files are in /root/hint{1,2}.txt, answer file is in /root/solution.txt. Good luck!<3
