# Hints:
#  What is involved with networking in Openstack ?
#  Does our OpenStack host VM have property connectivity?
#  Are all the hops reachable trouhg the environment ?
#  Where can we configure network access to/from instances?
#  What security group does this VM belong to?
#
#
#
#
#
#
#
# (the first 10 lines are the hint, so pad with empty lines)

- hosts: all
  become: true
  tasks:

  - name: exercise setup step 1
    shell: source /root/keystonerc_admin && nova boot --flavor m1.tiny --image cirros --nic net-name=private --security-group default troubled_instance

  - name: exercise setup step 2
    shell: source /root/keystonerc_admin && nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0

  - name: exercise setup step 3
    shell: source /root/keystonerc_admin && neutron router-interface-delete router1 private_subnet

  - name: Description
    debug:
      msg: >
        Customer has reported that he can not reach his instance via ssh neither ping after a maintenance his team did last night.
        If you need a hint, run 'head breaks/break005.yml'
