#!/bin/bash

BREAKDIR='./breaks'

# If no breakfix was specified, select one at random
if [[ -e "$1" ]] ; then 
  BREAKTASKFILE="$1"
else
  # Choose random file
  ARR_INDEX=0
  for AVAILABLE_BREAK in $(ls ${BREAKDIR}/*yml)
  do
    BREAKFIXES[${ARR_INDEX}]=${AVAILABLE_BREAK}
    : $((ARR_INDEX++))
  done
  FILE_TO_CHOOSE=$((${RANDOM}%${ARR_INDEX-1}))
  BREAKTASKFILE=${BREAKFIXES[${FILE_TO_CHOOSE}]}
fi

echo $BREAKTASKFILE
export BREAKTASKFILE
vagrant up
