#!/bin/bash

BREAKDIR='./breaks'
COMPLETED_LABS=${BREAKDIR}/completed_labs
BREAKTASKFILE=
ARR_INDEX=0

choose_random_break_task_file ()
{
  ARR_INDEX=0
  for AVAILABLE_BREAK in $(ls ${BREAKDIR}/*yml)
  do  
    BREAKFIXES[${ARR_INDEX}]=${AVAILABLE_BREAK}
    : $((ARR_INDEX++))
  done
  FILE_TO_CHOOSE=$((${RANDOM}%${ARR_INDEX}))
  BREAKTASKFILE=${BREAKFIXES[${FILE_TO_CHOOSE}]}
}

update_completed_labs ()
{
  echo "${BREAKTASKFILE}" >> ${COMPLETED_LABS}
}

# If no breakfix was specified, select one at random
if [[ -e "$1" ]] ; then 
  BREAKTASKFILE="$1"
  
else
  # Choose random file
  COMPLETED_BEFORE=1
  NO_MORE_LABS=0
  RANDOM_TRIES=0
  until [ "${COMPLETED_BEFORE}" == "0" ] || [ "${NO_MORE_LABS}" == "1" ]
  do
    choose_random_break_task_file 
    if [ -e ${COMPLETED_LABS} ]
    then
      ! grep ${BREAKTASKFILE} ${COMPLETED_LABS} > /dev/null && \
      COMPLETED_BEFORE=0    
    else
      COMPLETED_BEFORE=0
    fi  
    : $((RANDOM_TRIES++))
    [ "${RANDOM_TRIES}" -gt "${ARR_INDEX}" ] && echo "You have completed all the exercises. Delete or edit ${COMPLETED_LABS} to try again" && NO_MORE_LABS=1 && exit 0
  done
fi

echo Lab selected: $BREAKTASKFILE
export BREAKTASKFILE
vagrant box add packstack http://86d05ef7a1e59a6e8a87-0f1aff6e20a80ba0fa046e04d0440490.r64.cf1.rackcdn.com/packstack.box --provider virtualbox
vagrant init packstack
sed -i '16i\ \ config.ssh.insert_key = false' Vagrantfile
sed -i '17i\ \ config.ssh.username = "vagrant"' Vagrantfile
sed -i '18i\ \ config.ssh.password = "vagrant"' Vagrantfile
vagrant up
echo 'localhost ansible_port=2222 ansible_user=root ansible_ssh_pass=rpcr' > localhost.config
ansible-playbook -i localhost.config $BREAKTASKFILE
[ "${?}" == "0" ] && update_completed_labs
